approval_policy = "never"
sandbox_mode = "danger-full-access"
cli_auth_credentials_store = "file"
model = "gpt-5.3-codex"
model_reasoning_effort = "high"

[sandbox_workspace_write]
network_access = true
writable_roots = [
  "/home/metr/dotfiles",
  "/home/metr/.config/hawk-cli",
  "/home/metr/.cache/uv"
]

[notice]
hide_full_access_warning = true

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.1-codex-mini" = "gpt-5.3-codex"

[features]
use_linux_sandbox_bwrap = true
